#Data Scientist

###Work Experience
- Data Analyst / Researcher (Remote) @ Edither Choice
* Developed and implemented advanced prediction models with accuracy rates exceeding 80%. Specialized in predicting diverse medical conditions, including coronary heart disease, pneumonia, and stroke, utilizing cutting-edge machine learning models and neural networks. 
* Co-authored a comprehensive thesis detailing the insights and discoveries from advanced predictive analytics of stroke among individuals from different geographic areas
* Trained regression models to determine the factors associated with the acquisition of health insurance improving customer acquisition by 20% through target marketing and customer retention by 53%.

Data Analyst (Freelance) @ Fraud Detection Analytics
* Trained multiple machine learning models to achieve over 90% accuracy in detecting fraudulent activities in web server log files.
* Deployed machine learning models for identifying fraudulent activities in e-commerce data with over 75% accuracy.

###Projects
